version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "dairy"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5s pg_isready -U postgres -h localhost -p 5432" ]
      interval: 10s
      retries: 10
      timeout: 60s  # Increased timeout to 60 seconds # Increased start_period to 60 seconds


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
